### ISSUE TITLE
PTB & Canary Support

### ISSUE THREAD

**Issue by HonkyToasty** [spookyorange/discord-linux-install#5]
I used the old script, but it's not working anymore. I deleted it and downloaded the latest one. But will it support PTB and canary clients (in perhaps future updates), like the old one does?

**Comment by spookyorange** [comment]
Hello there, the old script was installing it to /opt. It needed root privileges, that's why I've updated it to the local one.
I was not aware that the old one supported Canary/PTB clients.
I may update the /opt installation, if it has any bugs, please share more details, so that I can work on them.
*BTW I accidentally clicked close issue, my bad.

**Comment by HonkyToasty** [comment]
Am pretty sure that the old one supports Ptb and canary clients. I updated my ptb app using that script a couple times.

Uhhhh btw I actually wanted to open it as a pull request, but it says only constructors are allowed to do that.

Thanks for the reply anyway!

**Comment by spookyorange** [comment]
I'd like the project to continue on that support, thank you for bringing that problem up.
I'd love to work with you on that, I don't recall creating rules about PRs, did you try to fork the repo and create a PR from that repo?

**Comment by spookyorange** [comment]
Hello there, quick follow-up, I've wanted to make multiple versions possible and now found out Discord have changed the way their system works and now none of the installations work?
Anyway, I'm working on a convenient way to install any of 3 versions, I'm gonna release the fix as soon as possible, sorry for inconvenience*.

**Comment by HonkyToasty** [comment]
Sorry for the late reply, i dont go on github that often lol

I just DLed release 0.2.1 and it works like a charm. But there's indeed a small issue. You need to restart ur computer each time u update the app, which I found a little annoying.

Not a big deal, but I think the order is wrong. PTB is the beta of Discord, and canary is the alpha. So, if i were u, ill probably put ptb in second instead of third in the ui / script.

Also, i download the entire zip. I dont clone it, so i cant really help u with that sorry lol

**Comment by spookyorange** [comment]
Hmm, I've tested my scripts with GNOME and KDE Plasma, and they were fine after installs/updates, it should be about your DE or WM. Thing is that some DEs and WMs check for new apps in desktop app folders and update accordingly, perhaps yours does not, if you can share me details about your system I might be able to help?

Also about the Canary and PTB, from what I see, Canary is a tad more popular, hence I've taken action to make it appear before the PTB.

Have a good one!
